### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by Lakatoi** [namesys-eth/ccip2-eth-client#36]
When clicking the edit button from a ENS name I own the App breaks giving the following error: Application error: a client-side exception has occurred (see the browser console for more information).

The console gives the following:

Failed to load resource: the server responded with a status of 404 (Not Found)
ipfs.namesys.xyz:3003/read:1 
Failed to load resource: net::ERR_UNEXPECTED_PROXY_AUTH
ERROR: Failed to read from CCIP2 backend

**Comment by sshmatrix** [comment]
Hi @Lakatoi 👋

Can you try again and see if the issue is still persisting? We were making some fixes to our backend couple of days ago and you may have coincided with the downtime. If the issue still persists, can you tell us what ENS name it is? We can then check our backend logs to see what caused the error. Thanks for reporting the issue 🙏🏻

**Comment by Lakatoi** [comment]
Sorry, I opened a new issue [here](https://github.com/namesys-eth/ccip2-eth-backend/issues/2) because I didn't see your response. My ENS name is mtorra.eth.
